#!/usr/bin/env bash


if [[ $* = *[!\ ]* ]]; then
  params=( "$*" )
else
  params=( bash )
fi

COCO_DEV_IMAGE=jamieleecho/coco-dev:0.78

case "$(uname -s)" in

   Darwin)
     docker run -it --rm -w "$(pwd | sed -e s#^/[Uu][Ss][Ee][Rr][Ss]#/home#)" -v "$HOME"/..:/home -e HOME=/home/"$USER" ${COCO_DEV_IMAGE} ${params[@]}
     ;;

   Linux)
     docker run -u "$(id -u):$(id -g)" -it --rm -w "$(pwd)" -v /etc/passwd:/etc/passwd -v "$HOME"/..:/home -e HOME=/home/"$USER" ${COCO_DEV_IMAGE} ${params[@]}
     ;;

   CYGWIN*|MINGW32*|MSYS*)
     echo 'MS Windows not supported yet'
     ;;

   # Add here more strings to compare
   # See correspondence table at the bottom of this answer

   *)
     echo 'Unknown OS not supported' 
     ;;
esac

