#!/usr/bin/env sh


if [[ $* = *[!\ ]* ]]; then
  params=( -c "$*" )
else
  params=()
fi

case "$(uname -s)" in

   Darwin)
     docker-compose -f docker-compose.yml run --rm -w `pwd | sed -e s#^/[Uu][Ss][Ee][Rr][Ss]#/home#` coco-dev bash "${params[@]}"
     ;;

   Linux)
     docker-compose -f docker-compose.yml run --rm -w `pwd | sed -e s#^/[Uu][Ss][Ee][Rr][Ss]#/home#` coco-dev bash "${params[@]}"
     ;;

   CYGWIN*|MINGW32*|MSYS*)
     echo 'MS Windows not supported yet'
     ;;

   # Add here more strings to compare
   # See correspondence table at the bottom of this answer

   *)
     echo 'Unknown OS not supported' 
     ;;
esac

